CREATE TABLE client
(
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	surname VARCHAR(60) NOT NULL,
	email VARCHAR(60) NOT NULL
);

CREATE TABLE city
(
	id SERIAL PRIMARY KEY,
	name VARCHAR(30) NOT NULL  
);